###############################################################################
# SHCF – Smart Humidity Control Framework
# Core Package
###############################################################################

template: !include_dir_merge_list templates

automation: !include_dir_merge_list automations

input_select: !include helpers/input_select.yaml

input_number: !include helpers/input_number.yaml

timer: !include helpers/timers.yaml
