#!/usr/bin/env bash

###############################################################################
#
# SHCF Dashboard Builder
#
# Builds one shared Home Assistant dashboard from all generated SHCF
# device views.
#
###############################################################################

set -euo pipefail

if [ ! -d ".git" ]; then
    echo "ERROR: Please run this script from the repository root."
    exit 1
fi

GENERATED_DIR="packages/shcf/generated"
OUTPUT_FILE="${GENERATED_DIR}/shcf_dashboard.yaml"

mkdir -p "${GENERATED_DIR}"

VIEW_FILES=(
    "${GENERATED_DIR}"/device_*.view.yaml
)

if [ ! -e "${VIEW_FILES[0]}" ]; then
    echo "ERROR: No generated SHCF device views found in:"
    echo "  ${GENERATED_DIR}"
    exit 1
fi

{
    echo "# ============================================================================"
    echo "# SHCF Shared Dashboard"
    echo "# ============================================================================"
    echo "#"
    echo "# Generated automatically from SHCF device views."
    echo "# Do not edit this file manually."
    echo "#"
    echo "# ============================================================================"
    echo
    echo "title: SHCF - Smart Humidity Control Framework"
    echo "views:"

    for view_file in "${VIEW_FILES[@]}"; do
        echo
        echo "  # --------------------------------------------------------------------------"
        echo "  # Source: ${view_file}"
        echo "  # --------------------------------------------------------------------------"

        awk '
            BEGIN {
                view_started = 0
            }

            /^[[:space:]]*type:[[:space:]]*sections[[:space:]]*$/ && view_started == 0 {
                print "  - " $0
                view_started = 1
                next
            }

            {
                if (view_started == 1) {
                print "    " $0
                } else {
                print "  " $0
                }
            }
            ' "${view_file}"
    echo
    done
} > "${OUTPUT_FILE}"

echo
echo "Generated shared SHCF dashboard:"
echo "  ${OUTPUT_FILE}"
echo
echo "Included device views:"

for view_file in "${VIEW_FILES[@]}"; do
    echo "  ✔ ${view_file}"
done