#!/usr/bin/env bash

set -euo pipefail

if [ ! -d ".git" ]; then
  echo "Error: run this script from the repository root."
  exit 1
fi

read -rp "Display name, e.g. Trotec TTK 171 ECO 2: " DISPLAY_NAME
read -rp "Switching device entity, e.g. switch.zwischenstecker_2: " SWITCH_ENTITY
read -rp "Humidity sensor entity, e.g. sensor.sensor_2_humidity: " HUMIDITY_SENSOR
read -rp "Temperature sensor entity, e.g. sensor.sensor_2_temperature: " TEMPERATURE_SENSOR

INSTANCE_HASH="$(printf "%s" "${SWITCH_ENTITY}|${HUMIDITY_SENSOR}|${TEMPERATURE_SENSOR}" | shasum -a 1 | cut -c1-8)"
INSTANCE_ID="unit_${INSTANCE_HASH}"

INSTANCE_DIR="packages/shcf/instances"
DASHBOARD_DIR="packages/shcf/dashboards"

INSTANCE_FILE="${INSTANCE_DIR}/${INSTANCE_ID}.yaml"
DASHBOARD_FILE="${DASHBOARD_DIR}/${INSTANCE_ID}.yaml"

mkdir -p "${INSTANCE_DIR}"
mkdir -p "${DASHBOARD_DIR}"

if [ -f "${INSTANCE_FILE}" ]; then
  echo "Error: SHCF instance already exists:"
  echo "${INSTANCE_FILE}"
  exit 1
fi

cat > "${INSTANCE_FILE}" <<EOF
# SHCF Instance: ${DISPLAY_NAME}
# Instance ID: ${INSTANCE_ID}
# Generated by tools/create_shcf_instance.sh

input_select:
  shcf_${INSTANCE_ID}_operating_mode:
    name: SHCF ${DISPLAY_NAME} Operating Mode
    options:
      - Off
      - Automatic
      - Continuous Operation
      - Timed Operation
    initial: Off

input_number:
  shcf_${INSTANCE_ID}_target_humidity:
    name: SHCF ${DISPLAY_NAME} Target Humidity
    min: 35
    max: 75
    step: 1
    unit_of_measurement: "%"
    mode: slider
    initial: 60

  shcf_${INSTANCE_ID}_hysteresis:
    name: SHCF ${DISPLAY_NAME} Hysteresis
    min: 1
    max: 15
    step: 1
    unit_of_measurement: "%"
    mode: slider
    initial: 5

  shcf_${INSTANCE_ID}_timed_operation_minutes:
    name: SHCF ${DISPLAY_NAME} Timed Operation Minutes
    min: 5
    max: 720
    step: 5
    unit_of_measurement: "min"
    mode: box
    initial: 60

timer:
  shcf_${INSTANCE_ID}_timed_operation:
    name: SHCF ${DISPLAY_NAME} Timed Operation

template:
  - sensor:
      - name: SHCF ${DISPLAY_NAME} Current Humidity
        unique_id: shcf_${INSTANCE_ID}_current_humidity
        unit_of_measurement: "%"
        state: "{{ states('${HUMIDITY_SENSOR}') | float(0) }}"

      - name: SHCF ${DISPLAY_NAME} Current Temperature
        unique_id: shcf_${INSTANCE_ID}_current_temperature
        unit_of_measurement: "°C"
        state: "{{ states('${TEMPERATURE_SENSOR}') | float(0) }}"

      - name: SHCF ${DISPLAY_NAME} Target Humidity
        unique_id: shcf_${INSTANCE_ID}_target_humidity
        unit_of_measurement: "%"
        state: "{{ states('input_number.shcf_${INSTANCE_ID}_target_humidity') | float(60) }}"

      - name: SHCF ${DISPLAY_NAME} Switch-on Threshold
        unique_id: shcf_${INSTANCE_ID}_switch_on_threshold
        unit_of_measurement: "%"
        state: >
          {{ states('input_number.shcf_${INSTANCE_ID}_target_humidity') | float(60)
             + states('input_number.shcf_${INSTANCE_ID}_hysteresis') | float(5) }}

      - name: SHCF ${DISPLAY_NAME} Dehumidification Demand
        unique_id: shcf_${INSTANCE_ID}_dehumidification_demand
        state: >
          {% set humidity = states('${HUMIDITY_SENSOR}') | float(0) %}
          {% set target = states('input_number.shcf_${INSTANCE_ID}_target_humidity') | float(60) %}
          {% set threshold = states('sensor.shcf_${INSTANCE_ID}_switch_on_threshold') | float(65) %}
          {% if humidity <= target %}
            none
          {% elif humidity > threshold %}
            high
          {% else %}
            moderate
          {% endif %}

      - name: SHCF ${DISPLAY_NAME} Operating Status
        unique_id: shcf_${INSTANCE_ID}_operating_status
        state: >
          {% set mode = states('input_select.shcf_${INSTANCE_ID}_operating_mode') %}
          {% set switch_state = states('${SWITCH_ENTITY}') %}
          {% if mode == 'Off' %}
            Off
          {% elif mode == 'Continuous Operation' %}
            Continuous Operation
          {% elif mode == 'Timed Operation' %}
            Timed Operation
          {% elif mode == 'Automatic' and switch_state == 'on' %}
            Automatic Dehumidifying
          {% elif mode == 'Automatic' %}
            Automatic Standby
          {% else %}
            Unknown
          {% endif %}

automation:
  - id: shcf_${INSTANCE_ID}_controller
    alias: SHCF ${DISPLAY_NAME} Controller
    mode: restart

    trigger:
      - platform: time_pattern
        minutes: "/5"

      - platform: state
        entity_id:
          - ${HUMIDITY_SENSOR}
          - input_select.shcf_${INSTANCE_ID}_operating_mode
          - input_number.shcf_${INSTANCE_ID}_target_humidity
          - input_number.shcf_${INSTANCE_ID}_hysteresis
          - input_number.shcf_${INSTANCE_ID}_timed_operation_minutes

      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.shcf_${INSTANCE_ID}_timed_operation

    variables:
      mode_state: "{{ states('input_select.shcf_${INSTANCE_ID}_operating_mode') }}"
      humidity: "{{ states('${HUMIDITY_SENSOR}') | float(999) }}"
      target: "{{ states('input_number.shcf_${INSTANCE_ID}_target_humidity') | float(60) }}"
      threshold: "{{ states('sensor.shcf_${INSTANCE_ID}_switch_on_threshold') | float(65) }}"
      timer_active: "{{ is_state('timer.shcf_${INSTANCE_ID}_timed_operation', 'active') }}"
      duration: >
        {% set minutes = states('input_number.shcf_${INSTANCE_ID}_timed_operation_minutes') | int(60) %}
        {{ '%02d:%02d:%02d' | format(minutes // 60, minutes % 60, 0) }}

    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ trigger.platform == 'state'
                     and trigger.entity_id == 'input_select.shcf_${INSTANCE_ID}_operating_mode'
                     and trigger.to_state is not none
                     and trigger.to_state.state == 'Timed Operation' }}
            sequence:
              - service: timer.start
                target:
                  entity_id: timer.shcf_${INSTANCE_ID}_timed_operation
                data:
                  duration: "{{ duration }}"
              - service: switch.turn_on
                target:
                  entity_id: ${SWITCH_ENTITY}

          - conditions:
              - condition: template
                value_template: >
                  {{ trigger.platform == 'state'
                     and trigger.entity_id == 'input_number.shcf_${INSTANCE_ID}_timed_operation_minutes'
                     and mode_state == 'Timed Operation'
                     and timer_active }}
            sequence:
              - service: timer.start
                target:
                  entity_id: timer.shcf_${INSTANCE_ID}_timed_operation
                data:
                  duration: "{{ duration }}"

          - conditions:
              - condition: template
                value_template: >
                  {{ trigger.platform == 'event'
                     and mode_state == 'Timed Operation' }}
            sequence:
              - service: input_select.select_option
                target:
                  entity_id: input_select.shcf_${INSTANCE_ID}_operating_mode
                data:
                  option: Automatic

          - conditions:
              - condition: template
                value_template: "{{ mode_state == 'Off' }}"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: ${SWITCH_ENTITY}

          - conditions:
              - condition: template
                value_template: "{{ mode_state == 'Continuous Operation' }}"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: ${SWITCH_ENTITY}

          - conditions:
              - condition: template
                value_template: >
                  {{ mode_state == 'Automatic'
                     and humidity > threshold }}
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: ${SWITCH_ENTITY}

          - conditions:
              - condition: template
                value_template: >
                  {{ mode_state == 'Automatic'
                     and humidity <= target }}
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: ${SWITCH_ENTITY}
EOF

cat > "${DASHBOARD_FILE}" <<EOF
title: SHCF ${DISPLAY_NAME}
views:
  - title: Overview
    path: shcf-${INSTANCE_ID}
    cards:
      - type: entities
        title: SHCF ${DISPLAY_NAME} Control
        entities:
          - entity: input_select.shcf_${INSTANCE_ID}_operating_mode
            name: Operating Mode
          - entity: input_number.shcf_${INSTANCE_ID}_target_humidity
            name: Target Humidity
          - entity: input_number.shcf_${INSTANCE_ID}_hysteresis
            name: Hysteresis
          - entity: input_number.shcf_${INSTANCE_ID}_timed_operation_minutes
            name: Timed Operation Minutes
          - entity: timer.shcf_${INSTANCE_ID}_timed_operation
            name: Timed Operation Timer

      - type: entities
        title: SHCF ${DISPLAY_NAME} Sensors
        entities:
          - entity: sensor.shcf_${INSTANCE_ID}_current_humidity
            name: Current Humidity
          - entity: sensor.shcf_${INSTANCE_ID}_current_temperature
            name: Current Temperature
          - entity: sensor.shcf_${INSTANCE_ID}_target_humidity
            name: Target Humidity
          - entity: sensor.shcf_${INSTANCE_ID}_switch_on_threshold
            name: Switch-on Threshold
          - entity: sensor.shcf_${INSTANCE_ID}_dehumidification_demand
            name: Dehumidification Demand
          - entity: sensor.shcf_${INSTANCE_ID}_operating_status
            name: Operating Status

      - type: entities
        title: SHCF ${DISPLAY_NAME} Device
        entities:
          - entity: ${SWITCH_ENTITY}
            name: Switching Device
          - entity: ${HUMIDITY_SENSOR}
            name: Source Humidity Sensor
          - entity: ${TEMPERATURE_SENSOR}
            name: Source Temperature Sensor
EOF

echo
echo "Created SHCF instance:"
echo "${INSTANCE_FILE}"
echo
echo "Created SHCF dashboard:"
echo "${DASHBOARD_FILE}"
echo
echo "Instance ID:"
echo "${INSTANCE_ID}"
echo
echo "Next steps:"
echo "1. Review generated files"
echo "2. Deploy to Home Assistant:"
echo "   ./tools/deploy_to_homeassistant.sh"
echo "3. Check Home Assistant configuration"
echo "4. Restart Home Assistant"
